from metaworld.env_dict import ALL_V3_ENVIRONMENTS_GOAL_HIDDEN, ALL_V3_ENVIRONMENTS_GOAL_OBSERVABLE

ALL_V2_ENVIRONMENTS_GOAL_HIDDEN = {k.replace('-v3', '-v2'): v for k, v in ALL_V3_ENVIRONMENTS_GOAL_HIDDEN.items()}
ALL_V2_ENVIRONMENTS_GOAL_OBSERVABLE = {k.replace('-v3', '-v2'): v for k, v in ALL_V3_ENVIRONMENTS_GOAL_OBSERVABLE.items()}

__all__ = ["ALL_V2_ENVIRONMENTS_GOAL_HIDDEN", "ALL_V2_ENVIRONMENTS_GOAL_OBSERVABLE"]
